name: flexx_bet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  get: ^4.6.5
  carousel_slider: ^4.2.1
  country_codes: ^2.2.0
  flutter_native_splash: ^2.3.0
  permission_handler: ^10.2.0
  flutter_map: ^4.0.0
  webview_flutter_android: ^2.8.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutterwave_standard: ^1.0.7
  google_sign_in: ^6.1.5
  fast_contacts: ^3.0.3
  pin_code_fields: ^8.0.1
  share_plus: ^6.3.2
  chewie: ^1.3.1
  video_player: ^2.8.2
  badges: ^3.1.1
  camera: ^0.10.4
  firebase_storage: ^11.2.3
  intl: ^0.18.1
  image_picker: ^0.8.7+3
  connectivity_plus: ^3.0.4
  cached_network_image: ^3.2.1
  country_code_picker: ^3.0.0
  flutter_svg: ^1.1.6
  timeago: ^3.4.0
  youtube_player_iframe: ^3.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.6.2
  webview_flutter: ^3.0.4
  cloud_firestore: ^4.8.0
  get_storage: ^2.1.1
  crypto: ^3.0.3
  csv: ^5.0.2
  http: ^0.13.0
  cupertino_icons: ^1.0.2
  latlong2: ^0.8.2
  appinio_swiper: ^2.0.3
  shared_preferences: ^2.2.2
  awesome_notifications_core: ^0.8.0
  english_words: ^4.0.0
  percent_indicator: ^4.2.3
  awesome_notifications_fcm: ^0.8.0
  awesome_notifications: ^0.8.2
  uuid: ^3.0.7
  flutter:
    sdk: flutter
  firebase_dynamic_links: ^5.4.8
  flutter_animate: ^4.3.0
  flutter_tiktok_sdk: ^0.2.6
  flutter_web_auth: ^0.5.0
  audioplayers: ^5.2.1
  visibility_detector: ^0.4.0+2
#  tiktok_login_flutter: ^1.0.0
  flutter_otp_text_field: ^1.1.1
  country_picker: ^2.0.23
  firebase_messaging: ^14.7.15
  fluttertoast: ^8.2.4
  share_screenshot_widget: ^0.0.5
  path_provider: ^2.1.2
  gradient_borders: ^1.0.0
  simple_gradient_text: ^1.3.0
  month_year_picker: ^0.3.0+1
#  local_auth: ^2.1.8

  emoji_picker_flutter: ^1.6.4
  loading_animation_widget: ^1.2.0+4
  flutter_html:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/video/
    - assets/audio/




  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
